/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SanasaBank.view.cashInHand;

import SanasaBank.controller.AccountController;
import SanasaBank.controller.CashInHandController;
import SanasaBank.model.CashInHand;
import SanasaBank.other.AutoGenarateID;
import SanasaBank.other.Validations;
import SanasaBank.view.main.Main;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kalhara
 */
public class CashInHandForm extends javax.swing.JDialog {

    /**
     * Creates new form CashInHandForm
     */
    private int n5000;
    private int n2000;
    private int n1000;
    private int n500;
    private int n100;
    private int n50;
    private int n20;
    private int n10;
    private int c10;
    private int c5;
    private int c2;
    private int c1;
    private double amount;
    private boolean isAdmin;

    public CashInHandForm(java.awt.Frame parent, boolean modal,boolean isAdmin) {
        super(parent, modal);
        initComponents();
        
        this.isAdmin=isAdmin;
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/money.png"));
        imagePanel.setImage(icon.getImage());

        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String curDate = simpleDateFormat.format(date);

        dateLabel.setText(curDate);

        setLocationRelativeTo(null);
    }

    private void setAmount() {
        boolean notNull = !note5000Text.getText().equals("") && !note2000Text.getText().equals("") && !note1000Text.getText().equals("") && !note500Text.getText().equals("") && !note100Text.getText().equals("") && !note50Text.getText().equals("") && !note20Text.getText().equals("") && !note100Text.getText().equals("") && !coin10Text.getText().equals("") && !coin5Text.getText().equals("") && !coin2Text.getText().equals("") && !coin1Text.getText().equals("");
        if (notNull) {
            n5000 = Integer.parseInt(note5000Text.getText());
            n2000 = Integer.parseInt(note2000Text.getText());
            n1000 = Integer.parseInt(note1000Text.getText());
            n500 = Integer.parseInt(note500Text.getText());
            n100 = Integer.parseInt(note100Text.getText());
            n50 = Integer.parseInt(note50Text.getText());
            n20 = Integer.parseInt(note20Text.getText());
            n10 = Integer.parseInt(note10Text.getText());
            c10 = Integer.parseInt(coin10Text.getText());
            c5 = Integer.parseInt(coin5Text.getText());
            c2 = Integer.parseInt(coin2Text.getText());
            c1 = Integer.parseInt(coin1Text.getText());

            amount = n5000 * 5000 + n2000 * 2000 + n1000 * 1000 + n500 * 500 + n100 * 100 + n50 * 50 + n20 * 20 + n10 * 10 + c10 * 10 + c5 * 5 + c2 * 2 + c1 * 1;
            amountText.setText(String.format("%.2f", amount));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new org.jdesktop.swingx.JXImagePanel();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        note5000Text = new javax.swing.JTextField();
        note1000Text = new javax.swing.JTextField();
        note2000Text = new javax.swing.JTextField();
        note500Text = new javax.swing.JTextField();
        note50Text = new javax.swing.JTextField();
        note100Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        note20Text = new javax.swing.JTextField();
        note10Text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        coin10Text = new javax.swing.JTextField();
        coin5Text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        coin2Text = new javax.swing.JTextField();
        coin1Text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("date");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("5000 note  :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("2000 note  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("1000 note  :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("100 note   :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("500 note   :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("50 note    :");

        note5000Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note5000Text.setText("0");
        note5000Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note5000TextActionPerformed(evt);
            }
        });
        note5000Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note5000TextKeyReleased(evt);
            }
        });

        note1000Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note1000Text.setText("0");
        note1000Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note1000TextActionPerformed(evt);
            }
        });
        note1000Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note1000TextKeyReleased(evt);
            }
        });

        note2000Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note2000Text.setText("0");
        note2000Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note2000TextActionPerformed(evt);
            }
        });
        note2000Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note2000TextKeyReleased(evt);
            }
        });

        note500Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note500Text.setText("0");
        note500Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note500TextActionPerformed(evt);
            }
        });
        note500Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note500TextKeyReleased(evt);
            }
        });

        note50Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note50Text.setText("0");
        note50Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note50TextActionPerformed(evt);
            }
        });
        note50Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note50TextKeyReleased(evt);
            }
        });

        note100Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note100Text.setText("0");
        note100Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note100TextActionPerformed(evt);
            }
        });
        note100Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note100TextKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("20 note   :");

        note20Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note20Text.setText("0");
        note20Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note20TextActionPerformed(evt);
            }
        });
        note20Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note20TextKeyReleased(evt);
            }
        });

        note10Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        note10Text.setText("0");
        note10Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note10TextActionPerformed(evt);
            }
        });
        note10Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                note10TextKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("10 note   :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("10 voin    :");

        coin10Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin10Text.setText("0");
        coin10Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin10TextActionPerformed(evt);
            }
        });
        coin10Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coin10TextKeyReleased(evt);
            }
        });

        coin5Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin5Text.setText("0");
        coin5Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin5TextActionPerformed(evt);
            }
        });
        coin5Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coin5TextKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("5 coin    :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("2 coin    :");

        coin2Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin2Text.setText("0");
        coin2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin2TextActionPerformed(evt);
            }
        });
        coin2Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coin2TextKeyReleased(evt);
            }
        });

        coin1Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin1Text.setText("0");
        coin1Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coin1TextKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("1 coin    :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Amount  :");

        amountText.setEditable(false);
        amountText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        amountText.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Rs");

        exitButton.setBackground(new java.awt.Color(51, 102, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(51, 102, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(note5000Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note50Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note100Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note500Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note1000Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note2000Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(note20Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coin1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coin2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coin5Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coin10Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note10Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note5000Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(imagePanelLayout.createSequentialGroup()
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(note2000Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(16, 16, 16)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(note1000Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(note500Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(note100Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(note50Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addGap(25, 25, 25)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(note20Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(imagePanelLayout.createSequentialGroup()
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(note10Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(coin10Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(coin5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(coin2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(coin1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void note5000TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note5000TextKeyReleased
        Validations.noteCountValidation(note5000Text);
        setAmount();
    }//GEN-LAST:event_note5000TextKeyReleased

    private void note5000TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note5000TextActionPerformed
        note2000Text.requestFocus();
    }//GEN-LAST:event_note5000TextActionPerformed

    private void note2000TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note2000TextActionPerformed
        note1000Text.requestFocus();
    }//GEN-LAST:event_note2000TextActionPerformed

    private void note1000TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note1000TextActionPerformed
        note500Text.requestFocus();
    }//GEN-LAST:event_note1000TextActionPerformed

    private void note500TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note500TextActionPerformed
        note100Text.requestFocus();
    }//GEN-LAST:event_note500TextActionPerformed

    private void note100TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note100TextActionPerformed
        note50Text.requestFocus();
    }//GEN-LAST:event_note100TextActionPerformed

    private void note50TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note50TextActionPerformed
        note20Text.requestFocus();
    }//GEN-LAST:event_note50TextActionPerformed

    private void note20TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note20TextActionPerformed
        note10Text.requestFocus();
    }//GEN-LAST:event_note20TextActionPerformed

    private void note10TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note10TextActionPerformed
        coin10Text.requestFocus();
    }//GEN-LAST:event_note10TextActionPerformed

    private void coin10TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin10TextActionPerformed
        coin5Text.requestFocus();
    }//GEN-LAST:event_coin10TextActionPerformed

    private void coin5TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin5TextActionPerformed
        coin2Text.requestFocus();
    }//GEN-LAST:event_coin5TextActionPerformed

    private void coin2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin2TextActionPerformed
        coin1Text.requestFocus();
    }//GEN-LAST:event_coin2TextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            CashInHand cashInHand = new CashInHand(AutoGenarateID.genarate(null, "C", CashInHandController.getLastCashInHandID()), dateLabel.getText(), n5000, n2000, n1000, n500, n100, n50, n20, n10, c10, c5, c2, c1, amount, 0, amount, "open");
            int res = CashInHandController.addCashInHand(cashInHand);
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Added success ..  Press ok to load main...");
                this.dispose();
                new Main(this.isAdmin).setVisible(true);
                AccountController.updateInterest();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CashInHandForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CashInHandForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void note2000TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note2000TextKeyReleased
        Validations.noteCountValidation(note2000Text);
        setAmount();// TODO add your handling code here:
        
    }//GEN-LAST:event_note2000TextKeyReleased

    private void note1000TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note1000TextKeyReleased
        Validations.noteCountValidation(note1000Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note1000TextKeyReleased

    private void note500TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note500TextKeyReleased
        Validations.noteCountValidation(note500Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note500TextKeyReleased

    private void note100TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note100TextKeyReleased
        Validations.noteCountValidation(note100Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note100TextKeyReleased

    private void note50TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note50TextKeyReleased
        Validations.noteCountValidation(note50Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note50TextKeyReleased

    private void note20TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note20TextKeyReleased
        Validations.noteCountValidation(note20Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note20TextKeyReleased

    private void note10TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_note10TextKeyReleased
        Validations.noteCountValidation(note10Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_note10TextKeyReleased

    private void coin10TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coin10TextKeyReleased
        Validations.noteCountValidation(coin10Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_coin10TextKeyReleased

    private void coin5TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coin5TextKeyReleased
        Validations.noteCountValidation(coin5Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_coin5TextKeyReleased

    private void coin2TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coin2TextKeyReleased
        Validations.noteCountValidation(coin2Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_coin2TextKeyReleased

    private void coin1TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coin1TextKeyReleased
        Validations.noteCountValidation(coin1Text);
        setAmount();        // TODO add your handling code here:
        
    }//GEN-LAST:event_coin1TextKeyReleased

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(3);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashInHandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashInHandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashInHandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashInHandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashInHandForm dialog = new CashInHandForm(new javax.swing.JFrame(), true,false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountText;
    private javax.swing.JTextField coin10Text;
    private javax.swing.JTextField coin1Text;
    private javax.swing.JTextField coin2Text;
    private javax.swing.JTextField coin5Text;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton exitButton;
    private org.jdesktop.swingx.JXImagePanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField note1000Text;
    private javax.swing.JTextField note100Text;
    private javax.swing.JTextField note10Text;
    private javax.swing.JTextField note2000Text;
    private javax.swing.JTextField note20Text;
    private javax.swing.JTextField note5000Text;
    private javax.swing.JTextField note500Text;
    private javax.swing.JTextField note50Text;
    // End of variables declaration//GEN-END:variables
}
