/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SanasaBank.view.loan;

import SanasaBank.controller.BillNumberContraller;
import SanasaBank.controller.CashInHandController;
import SanasaBank.controller.GuaranteeController;
import SanasaBank.controller.LoanController;
import SanasaBank.controller.LoanTypeController;
import SanasaBank.controller.MemberController;
import SanasaBank.controller.PropertyController;
import SanasaBank.model.Guarantee;
import SanasaBank.model.Loan;
import SanasaBank.model.Member;
import SanasaBank.model.Property;
import SanasaBank.other.AutoGenarateID;
import SanasaBank.other.Validations;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kalhara
 */
public class NewLoanForm extends javax.swing.JFrame {

    /**
     * Creates new form LoanDetail
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public static Property property;

    public NewLoanForm() throws ClassNotFoundException, SQLException {
        initComponents();
        ImageIcon icon=new ImageIcon(getClass().getResource("/image/label.png"));
        imagePanel2.setImage(icon.getImage());

      //  setLocationRelativeTo(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize);

        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String curDate = simpleDateFormat.format(date);

        dateLabel.setText(curDate);

        setBillNumber();
        setLoanId();

        ArrayList<String> loanTypeList = LoanTypeController.getAllLoanType();
        for (String loanType : loanTypeList) {
            loanTypeCombo.addItem(loanType);
        }
        loanTypeCombo.setSelectedIndex(-1);
        memberIDText.requestFocus();

    }

    private void setBillNumber() throws ClassNotFoundException, SQLException {
        String lastNumber = BillNumberContraller.getLastNumber();
        AutoGenarateID.genarate(billNumberLabel, "", lastNumber);

    }

    private void setLoanId() throws SQLException, ClassNotFoundException {

        String lastId = LoanController.getLastId();
        AutoGenarateID.genarate(loanIDLabel, "L", lastId);
    }

    private void emptyAll() {
        memberIDText.setText("");
        nameLabel.setText("");
        loanTypeCombo.setSelectedIndex(-1);
        rateLabel.setText("");
        amountText.setText("");
        instalmentCountText.setText("");
        instalmentLabel.setText("");
        durationLabel.setText("");
        firstPaymentDateLabel.setText("");
        firstPaymentLabel.setText("");
        guarantor1Text.setText("");
        guarantor2Text.setText("");
        
    }

    private void ifAllFilled() {
        boolean filled = !memberIDText.getText().equals("") && loanTypeCombo.getSelectedIndex() != -1 && !amountText.getText().equals("") && !instalmentCountText.getText().equals("");
        if (filled) {
            proccessButton.setEnabled(true);
        } else {
            proccessButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new org.jdesktop.swingx.JXImagePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        loanIDLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        memberIDText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loanTypeCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        instalmentCountText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        instalmentLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstPaymentDateLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        firstPaymentLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        guarantor1Text = new javax.swing.JTextField();
        guarantor2Text = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        proccessButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        propertyChekBox = new javax.swing.JCheckBox();
        addPropertyButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        imagePanel2 = new org.jdesktop.swingx.JXImagePanel();
        dateLabel = new javax.swing.JLabel();
        billNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loan Details", 0, 0, new java.awt.Font("Bodoni MT", 3, 36), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Loan Id  :");

        loanIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loanIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Member ID  :");

        memberIDText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        memberIDText.setToolTipText("Insert member ID...");
        memberIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDTextActionPerformed(evt);
            }
        });
        memberIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                memberIDTextKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Rate  :");

        rateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("%");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Loan Type  :");

        loanTypeCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loanTypeCombo.setToolTipText("Selwct loan type...");
        loanTypeCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loanTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeComboActionPerformed(evt);
            }
        });
        loanTypeCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loanTypeComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loanTypeComboKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name  :");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Amount :");

        amountText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountText.setToolTipText("Insert loan amount...");
        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });
        amountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTextKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Rs ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Instalment Count  :");

        instalmentCountText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instalmentCountText.setToolTipText("Insert instalment count");
        instalmentCountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instalmentCountTextActionPerformed(evt);
            }
        });
        instalmentCountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                instalmentCountTextKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Instalment  :");

        instalmentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instalmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Rs ");

        durationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("First Payment Date  :");

        firstPaymentDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstPaymentDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("First Payment  :");

        firstPaymentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Rs ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Guarantors  :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("1 - ");

        guarantor1Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guarantor1Text.setToolTipText("Insert guarantor...");
        guarantor1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarantor1TextActionPerformed(evt);
            }
        });

        guarantor2Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guarantor2Text.setToolTipText("Insert guarantor...");
        guarantor2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarantor2TextActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("2 - ");

        proccessButton.setBackground(new java.awt.Color(0, 51, 255));
        proccessButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        proccessButton.setForeground(new java.awt.Color(255, 255, 255));
        proccessButton.setText("Proccess");
        proccessButton.setToolTipText("Proccess...");
        proccessButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proccessButton.setEnabled(false);
        proccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proccessButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(0, 51, 255));
        clearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setToolTipText("Cleare all");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        propertyChekBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propertyChekBox.setText("  Is mortgaging required?");
        propertyChekBox.setToolTipText("Property required...");
        propertyChekBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyChekBoxActionPerformed(evt);
            }
        });
        propertyChekBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                propertyChekBoxKeyReleased(evt);
            }
        });

        addPropertyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addPropertyButton.setText("Add Property");
        addPropertyButton.setToolTipText("Add property...");
        addPropertyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPropertyButton.setEnabled(false);
        addPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropertyButtonActionPerformed(evt);
            }
        });

        checkButton.setBackground(new java.awt.Color(0, 51, 255));
        checkButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkButton.setForeground(new java.awt.Color(255, 255, 255));
        checkButton.setText("CHEK");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addComponent(loanIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(memberIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(loanTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(676, 676, 676)
                        .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11)
                        .addGap(13, 13, 13)
                        .addComponent(firstPaymentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(257, 257, 257)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(instalmentCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(instalmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(256, 256, 256)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(propertyChekBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(addPropertyButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(firstPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(proccessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(10, 10, 10)
                                .addComponent(guarantor1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel19)
                                .addGap(10, 10, 10)
                                .addComponent(guarantor2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(loanIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(memberIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(loanTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instalmentCountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addGap(11, 11, 11)
                .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12))
                    .addComponent(instalmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(firstPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(firstPaymentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertyChekBox)
                    .addComponent(addPropertyButton))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guarantor1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(guarantor2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(proccessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date");

        billNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billNumberLabel.setText("bill number");

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel2Layout.createSequentialGroup()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(billNumberLabel))
        );

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDTextActionPerformed
        try {
            Member member = MemberController.getMemberDetail(memberIDText.getText());
            if (member != null) {
                nameLabel.setText(member.getName());
                loanTypeCombo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, memberIDText.getText() + " Member not found");
                memberIDText.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memberIDTextActionPerformed

    private void loanTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeComboActionPerformed

    }//GEN-LAST:event_loanTypeComboActionPerformed

    private void loanTypeComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTypeComboKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                String loanType = (String) loanTypeCombo.getSelectedItem();
                try {
                    String rate = Integer.toString(LoanTypeController.getLoanRate(loanType));
                    rateLabel.setText(rate);
                    amountText.requestFocus();
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_loanTypeComboKeyPressed

    private void instalmentCountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instalmentCountTextActionPerformed
        double amount = Double.parseDouble(amountText.getText());
        int count = Integer.parseInt(instalmentCountText.getText());
        double instalment = amount / count;
        instalmentLabel.setText(String.format("%.2f", instalment));
        int month = count % 12;
        int year = count / 12;
        if (year > 0 && month != 0) {
            durationLabel.setText(year + " Years and " + month + " Months");
        } else if (month == 0) {
            durationLabel.setText(year + " Years");
        } else {
            durationLabel.setText(month + " Months");
        }
        Calendar calendar = Calendar.getInstance();
        calendar.roll(Calendar.MONTH, 1);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date firstPaymentDate = calendar.getTime();
        firstPaymentDateLabel.setText(sdf.format(firstPaymentDate));

        double interest = Double.parseDouble(amountText.getText()) * Integer.parseInt(rateLabel.getText()) * 30 / (365 * 100);
        double firstPayment = (instalment + interest);

        firstPaymentLabel.setText(String.format("%.2f", firstPayment));
        guarantor1Text.requestFocus();
    }//GEN-LAST:event_instalmentCountTextActionPerformed

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        instalmentCountText.requestFocus();
    }//GEN-LAST:event_amountTextActionPerformed

    private void guarantor1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarantor1TextActionPerformed
        try {
            Member member = MemberController.getMemberDetail(guarantor1Text.getText());
            if (member != null) {
                guarantor2Text.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, guarantor1Text.getText() + " Member not found");
                guarantor1Text.setText("");
                guarantor1Text.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guarantor1TextActionPerformed

    private void guarantor2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarantor2TextActionPerformed

        try {
            Member member = MemberController.getMemberDetail(guarantor2Text.getText());
            if (member != null) {
                propertyChekBox.requestFocus();
                propertyChekBox.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(null, guarantor2Text.getText() + " Member not found");
                guarantor2Text.setText("");
                guarantor2Text.requestFocus();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_guarantor2TextActionPerformed

    private void proccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proccessButtonActionPerformed
        try {
            Loan loan = new Loan(loanIDLabel.getText(), memberIDText.getText(), LoanTypeController.getLoanTypeID((String) loanTypeCombo.getSelectedItem()), CashInHandController.getLastCashInHandID(), Double.parseDouble(amountText.getText()), Integer.parseInt(instalmentCountText.getText()), dateLabel.getText(), Double.parseDouble(amountText.getText()), Double.parseDouble(instalmentLabel.getText()), firstPaymentDateLabel.getText(), dateLabel.getText(), 0);
            int res = LoanController.addLoan(loan);

            Guarantee guarantees[] = new Guarantee[2];
            for (int i = 0; i < 2; i++) {
                guarantees[i] = new Guarantee();
                guarantees[i].setLID(loanIDLabel.getText());
            }
            guarantees[0].setMID(guarantor1Text.getText());
            guarantees[1].setMID(guarantor2Text.getText());
            int res2 = GuaranteeController.addGuarantors(guarantees[0]);
            int res3 = GuaranteeController.addGuarantors(guarantees[1]);

            CashInHandController.updateCashInHand(-Double.parseDouble(amountText.getText()));
            if (this.property != null) {
                PropertyController.addProperty(this.property);
            }

            if (res > 0 && res2 > 0 && res3 > 0) {
                JOptionPane.showMessageDialog(null, "Success...");
                BillNumberContraller.addBillNumber(Integer.parseInt(billNumberLabel.getText()));

                setLoanId();
                setBillNumber();
                emptyAll();
                memberIDText.requestFocus();
                proccessButton.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Error...");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_proccessButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure that you want to cancel this loan", "Confirm", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            emptyAll();
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void propertyChekBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyChekBoxActionPerformed
        if (propertyChekBox.isSelected()) {
            addPropertyButton.setEnabled(true);
        } else {
            addPropertyButton.setEnabled(false);
        }
    }//GEN-LAST:event_propertyChekBoxActionPerformed

    private void addPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyButtonActionPerformed
        try {
            new PropertyDialog(this, true, loanIDLabel.getText()).setVisible(true);
            proccessButton.requestFocus();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPropertyButtonActionPerformed

    private void propertyChekBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_propertyChekBoxKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            propertyChekBox.doClick();
        } else if (propertyChekBox.isSelected() && evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            addPropertyButton.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            proccessButton.requestFocus();
        }
    }//GEN-LAST:event_propertyChekBoxKeyReleased

    private void memberIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberIDTextKeyReleased
        ifAllFilled();
    }//GEN-LAST:event_memberIDTextKeyReleased

    private void amountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyReleased
        ifAllFilled();
        Validations.balanceValidation(amountText);
    }//GEN-LAST:event_amountTextKeyReleased

    private void loanTypeComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTypeComboKeyReleased
        ifAllFilled();
    }//GEN-LAST:event_loanTypeComboKeyReleased

    private void instalmentCountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instalmentCountTextKeyReleased
        ifAllFilled();        // TODO add your handling code here:
        Validations.accountNumberValidation(instalmentCountText);
    }//GEN-LAST:event_instalmentCountTextKeyReleased

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        try {
            new CheckForm().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new NewLoanForm().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(NewLoanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPropertyButton;
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel billNumberLabel;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel firstPaymentDateLabel;
    private javax.swing.JLabel firstPaymentLabel;
    private javax.swing.JTextField guarantor1Text;
    private javax.swing.JTextField guarantor2Text;
    private org.jdesktop.swingx.JXImagePanel imagePanel;
    private org.jdesktop.swingx.JXImagePanel imagePanel2;
    private javax.swing.JTextField instalmentCountText;
    private javax.swing.JLabel instalmentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loanIDLabel;
    private javax.swing.JComboBox loanTypeCombo;
    private javax.swing.JTextField memberIDText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton proccessButton;
    private javax.swing.JCheckBox propertyChekBox;
    private javax.swing.JLabel rateLabel;
    // End of variables declaration//GEN-END:variables
}
